name: Hugo

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: ğŸš€ Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: ğŸ” SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        name: id_rsa
        known_hosts: ${{ secrets.KNOWN_HOSTS }}

    - name: ğŸ›’ Source
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        submodules: true

    - name: âœ¨ Hugo
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: 'latest'
        extended: true

    - name: ğŸ› ï¸ Build
      run: hugo --cleanDestinationDir --enableGitInfo --minify --noChmod --noTimes --verbose --printMemoryUsage --printPathWarnings --printUnusedTemplates --templateMetrics --templateMetricsHints -e production

    - name: ğŸš€ Deploy
      run: rsync --delete -4rvzh public/ w0ne@w0ne.org:/home/w0ne/public_html/news.w0ne.org
